config/routes.rb
Rails.application.routes.draw do

  post 'cart/create_charge' => 'cart#create_charge', :as => :create_charge
  post '/cart/create_address' => 'cart#create_address', :as => :create_address
  get '/cart/place_order' => 'cart#place_order', :as => :place_order
  get '/cart/checkout' => 'cart#checkout', :as => :checkout
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear_cart', :as => :clear_cart
  get '/cart/:id' => 'cart#add'
  post '/cart/set_quantity' => 'cart#set_quantity'

  get 'store/:id' => 'store#show', :as => :store_product

  get 'login'   => 'user_sessions#new'
  get 'logout'  => 'user_sessions#destroy'

  get 'home/index', :as => :home
  get 'products/:id' => 'home#show', :as => :show_product

  resources :user_sessions, only: [:new, :create]
  
  post 'sign_up' => 'registration#create'
  get 'sign_up' => 'registration#new'
  

  scope :admin do
    get '' => 'admin#index'
    resources :products do
      resources :product_variants
    end
    resources :users
    resources :categories
    resources :brands
    resources :colors
  end

  root 'home#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :products

	validates :name, presence:true, length: { in: 2..20 }
	validates :description, length: { maximum: 50 }
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	validates :quantity, presence:true

	def self.quantity_options
    	(1..10).to_a.collect{|p| ["#{p}", p]}
  	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products

	validates :name, presence:true, length: { in: 3..20 }
	validates :description, length: { maximum: 50 }
end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :product_variants

	validates :name, presence:true
	validates :hex, presence:true

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
  belongs_to :brand
  has_many :product_variants
  has_many :cart_items

  accepts_nested_attributes_for :product_variants, allow_destroy: true

	validates :title, presence:true, length: { in: 3..20 }
	validates :price, presence:true
  validates :category_id, presence:true
  validates :brand_id, presence:true
  validates :description, length: { maximum: 80 }

	has_attached_file :image,
  	:storage => :s3,
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  

  validates_attachment :image,
  	:presence => true,
  	:content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
  
  def s3_credentials
    {
      :bucket => ENV["S3_BUCKET"],
      :access_key_id => ENV["ACCESS_KEY_ID"],
      :secret_access_key => ENV["SECRET_ACCESS_KEY"]
    }
  end

  def self.get_discounted_items
    self.where("discount IS NOT NULL")
  end 

  def apply_discount
    price = self.price
    discount = self.discount
    return price if discount.nil?
    if discount.present?
        price = price - ((price / 100) * discount)
        return price
    end
  end

  def self.size_options
    (17..50).to_a.collect{|p| ["#{p}", p]}
  end
end

app/models/product_variant.rb
class ProductVariant < ActiveRecord::Base
	belongs_to :product
	belongs_to :color
	
	validates :size, presence:true
	validates :color_id, presence:true
	validates :quantity, presence:true, length: { maximum: 10000 }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
	belongs_to :user

	validates :full_name, presence:true, length: { in: 5..50 }
	validates :address, length: { maximum: 60 }
	validates :city, presence:true, length: { in: 3..50 }
	validates :state, length: { maximum: 50 }
	validates :zip, length: { maximum: 20 }
	validates :phone_number, length: { maximum: 20 }

	def country_name
    	c = ISO3166::Country[country]
    	c.translations[I18n.locale.to_s] || c.name
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_items
	has_many :shipping_addresses
  	rolify
	has_secure_password
	validates :password, presence:true, :on => :create, length: { in: 6..20 }
	validates :full_name, presence: true, length: { in: 6..50 }
	validates :email, presence: true, uniqueness: true,
										format: {
											with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
										}
	def total_quantity
		self.cart_items.sum(:quantity)
	end

	def total_price
		total = 0
		self.cart_items.each do |item|
			total += item.quantity * item.product.apply_discount
		end
		return total
	end

	def total_with_shipping
		total_price + 10
	end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :check_authentication, expect: [:index]
  before_action :set_no_sidebar
  
  def add
    @product_item = @current_user.cart_items.where("product_id = ?", params[:id]).first
    if @product_item
      @product_item.quantity = @product_item.quantity + 1
      @product_item.save
    else
      item = CartItem.new
      item.user = @current_user
      item.product = Product.find(params[:id])
      item.quantity = 1
      item.save
    end
    redirect_to :action => :index
  end

  def clear_cart
    @current_user.cart_items.delete_all
    redirect_to :action => :index
  end

  def index
    @cart_items = @current_user.cart_items.order(:id)
  end

  def set_quantity
    cart_item = @current_user.cart_items.find(params[:cart_item_id])
    quantity = params[:quantity]
    
    cart_item.quantity = quantity
    cart_item.save()

    redirect_to :action => :index
  end

  def checkout
    @addresses = @current_user.shipping_addresses
    @address = ShippingAddress.new
  end

  def place_order
    @address = ShippingAddress.find(params[:address_id])
  end

  def create_charge
      # Amount in cents
      tmp = @current_user.total_price * 100
      @amount_dollar = @current_user.total_price + 10
      @amount = tmp.to_i

      customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'ABH-Shoes order',
      :currency    => 'usd'
    )

    @current_user.cart_items.delete_all

  rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

  def create_address
    @address = ShippingAddress.new(shipping_address_params)
    @address.user = @current_user
    @address.save
    redirect_to "/cart/place_order?address_id=#{@address.id}"
  end


  private
    def shipping_address_params
      params.require(:shipping_address).permit(:full_name, :address, :city, :state, :zip, :country, :phone_number, :user_id)
    end

    def set_no_sidebar
      @no_sidebar = true
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@products = Product.all
		@products_tmp = Product.where("created_at > ?", Time.now - 15.days)
		@products_new = @products_tmp.where("discount IS NULL")
		@products_sale = Product.get_discounted_items
	end
	
	def show
		@product = Product.find(params[:id])
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def all_categories
		Category.all
	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row carousel-holder">

    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="http://i.imgur.com/qo4fmTi.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="http://i.imgur.com/5Lnkakp.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="http://i.imgur.com/sO3VDoL.jpg" alt="">
                </div>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <% @products_new.each { |product| %>
        <div class="col-xs-12 col-md-4 col-lg-4 product">
            <%= link_to show_product_path(product.id) do %>
            <div class="thumbnail">
            <span class="label newproduct">NEW</span>
               <%= image_tag product.image %>
                <div class="caption">
                    <h4 class="pull-right">$<%= product.price %></h4>
                    <h4 class="product-title"><%= product.title %></h4>
                    <p class="single-item-description"><%= product.description %></p>
            <% end %>
                    <a href="/cart/<%= product.id %>" class="btn btn-small btn-primary">Add To Cart</a>
                </div>
                <div class="ratings">
                    <p class="pull-right">15 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>
                </div>
            </div>
        </div>
   <% } %>
   <% @products_sale.each { |product| %>
        <div class="col-xs-12 col-md-4 col-lg-4 product">
            <%= link_to show_product_path(product.id) do %>
            <div class="thumbnail">
            <span class="label newproduct">SALE</span>
               <%= image_tag product.image %>
                <div class="caption">
                    <h4 class="line-through">$<%= product.price.round(2) %></h4>
                    <h4 class="pull-right price">$<%= product.apply_discount.round(2) %></h4>
                    <h4 class="product-title"><%= product.title %></h4>
                    <p class="single-item-description"><%= product.description %></p>
             <% end %>
                    <a href="/cart/<%= product.id %>" class="btn btn-small btn-primary">Add To Cart</a>
                </div>
                <div class="ratings">
                    <p class="pull-right">15 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>
                </div>
            </div>
        </div>
   <% } %>
</div>

app/views/home/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @product.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.apply_discount.round(2) %>$</dd>
   <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @product.category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brand_id) %>:</strong></dt>
  <dd><%= @product.brand.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag(@product.image, class: "menu_icon") %></dd>
  
</dl>