config/routes.rb
Rails.application.routes.draw do

  post 'cart/create_charge' => 'cart#create_charge', :as => :create_charge
  post '/cart/create_address' => 'cart#create_address', :as => :create_address
  get '/cart/place_order' => 'cart#place_order', :as => :place_order
  get '/cart/checkout' => 'cart#checkout', :as => :checkout
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear_cart', :as => :clear_cart
  get '/cart/:id' => 'cart#add'
  post '/cart/set_quantity' => 'cart#set_quantity'

  get 'store/:id' => 'store#show', :as => :store_product

  get 'login'   => 'user_sessions#new'
  get 'logout'  => 'user_sessions#destroy'

  get 'home/index', :as => :home
  get 'products/:id' => 'home#show', :as => :show_product

  resources :user_sessions, only: [:new, :create]
  
  post 'sign_up' => 'registration#create'
  get 'sign_up' => 'registration#new'
  

  scope :admin do
    get '' => 'admin#index'
    resources :products do
      resources :product_variants
    end
    resources :users
    resources :categories
    resources :brands
    resources :colors
  end

  root 'home#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :products

	validates :name, presence:true, length: { in: 2..20 }
	validates :description, length: { maximum: 50 }
end

app/controllers/brands_controller.rb
class BrandsController < AdminController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to @brand, notice: 'Brand was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /brands/1
  def update
    if @brand.update(brand_params)
      redirect_to @brand, notice: 'Brand was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /brands/1
  def destroy
    @brand.destroy
    redirect_to brands_url, notice: 'Brand was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :description)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for @brand, :html => { :class => "form-horizontal brand col-md-6 col-lg-7" } do |f| %>

    <% if @brand.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @brand.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label required' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control', maxlength: 20, required: true %>
    </div>
    <%= error_span(@brand[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control', maxlength: 50 %>
    </div>
    <%= error_span(@brand[:description]) %>
  </div>

  <div class="row">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              brands_path, :class => 'btn btn-default' %>
  </div>

  <script>
    $("form").change(function () {
      if (!window.onbeforeunload) {
        window.onbeforeunload = function() {
          return "You have unsaved changes.";
        };
      };
    })

    $("form").submit(function () {
      window.onbeforeunload = null;
    });
  </script>

<% end %>

app/views/brands/edit.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/brands/index.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:name) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:description) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
      <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td class="text-center"><%= link_to brand.id, brand_path(brand) %></td>
        <td class="text-center"><%= brand.name %></td>
        <td class="text-center description" title="<%= brand.description %>"><%= brand.description %></td>
        <td class="text-center"><%= brand.created_at.strftime("%b %d, %Y") %></td>
        <td class="text-center">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_brand_path(brand), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      brand_path(brand),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_brand_path,
              :class => 'btn btn-primary' %>
</div>

app/views/brands/new.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/brands/show.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @brand.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @brand.description %></dd>
 
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              brands_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_brand_path(@brand), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              brand_path(@brand),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>