config/routes.rb
Rails.application.routes.draw do

  post 'cart/create_charge' => 'cart#create_charge', :as => :create_charge
  post '/cart/create_address' => 'cart#create_address', :as => :create_address
  get '/cart/place_order' => 'cart#place_order', :as => :place_order
  get '/cart/checkout' => 'cart#checkout', :as => :checkout
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear_cart', :as => :clear_cart
  get '/cart/:id' => 'cart#add'
  post '/cart/set_quantity' => 'cart#set_quantity'

  get 'store/:id' => 'store#show', :as => :store_product

  get 'login'   => 'user_sessions#new'
  get 'logout'  => 'user_sessions#destroy'

  get 'home/index', :as => :home
  get 'products/:id' => 'home#show', :as => :show_product

  resources :user_sessions, only: [:new, :create]
  
  post 'sign_up' => 'registration#create'
  get 'sign_up' => 'registration#new'
  

  scope :admin do
    get '' => 'admin#index'
    resources :products do
      resources :product_variants
    end
    resources :users
    resources :categories
    resources :brands
    resources :colors
  end

  root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
  belongs_to :brand
  has_many :product_variants
  has_many :cart_items

  accepts_nested_attributes_for :product_variants, allow_destroy: true

	validates :title, presence:true, length: { in: 3..20 }
	validates :price, presence:true
  validates :category_id, presence:true
  validates :brand_id, presence:true
  validates :description, length: { maximum: 80 }

	has_attached_file :image,
  	:storage => :s3,
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  

  validates_attachment :image,
  	:presence => true,
  	:content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
  
  def s3_credentials
    {
      :bucket => ENV["S3_BUCKET"],
      :access_key_id => ENV["ACCESS_KEY_ID"],
      :secret_access_key => ENV["SECRET_ACCESS_KEY"]
    }
  end

  def self.get_discounted_items
    self.where("discount IS NOT NULL")
  end 

  def apply_discount
    price = self.price
    discount = self.discount
    return price if discount.nil?
    if discount.present?
        price = price - ((price / 100) * discount)
        return price
    end
  end

  def self.size_options
    (17..50).to_a.collect{|p| ["#{p}", p]}
  end
end

app/controllers/products_controller.rb
class ProductsController < AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.order(:name)
    @brands = Brand.order(:name)
    @colors = Color.order(:name)
    @product.product_variants.build
  end

  # GET /products/1/edit
  def edit
    @categories = Category.order(:name)
    @brands = Brand.order(:name)
    @colors = Color.order(:name)
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      @categories = Category.order(:name)
      @brands = Brand.order(:name)
      @colors = Color.order(:name)
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      @categories = Category.order(:name)
      @brands = Brand.order(:name)
      @colors = Color.order(:name)
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image, :category_id, :brand_id, :discount,
        product_variants_attributes: [:id, :size, :quantity, :color_id, :_destroy])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product col-md-6 col-lg-8" } do |f| %>

    <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label required' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control', maxlength: 20, required: true %>
    </div>
    <%= error_span(@product[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control', maxlength: 80 %>
    </div>
    <%= error_span(@product[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label required' %>
    <div class="left-inner-addon">
      <span>$</span>
      <div class="controls">
        <%= f.number_field :price, :step => 'any', :class => 'form-control', required: true %>
      </div>
    </div>
    <%= error_span(@product[:price]) %>
  </div>
   <div class="control-group">
    <%= f.label :image, :class => 'control-label required' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'form-control', required: @product.new_record? %>
    </div>
    <%= error_span(@product[:image]) %>
  </div>
   <div class="control-group">
    <%= f.label :category_id, :class => 'control-label required' %>
    <div class="controls">
      <%= f.collection_select :category_id, @categories, :id, :name, { include_blank: true }, {:class=>'form-control', required: true } %>
    </div>
    <%= error_span(@product[:category_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :brand_id, :class => 'control-label required' %>
    <div class="controls">
      <%= f.collection_select :brand_id, @brands, :id, :name, { include_blank: true }, {:class=>'form-control', required: true } %>
    </div>
    <%= error_span(@product[:brand_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :discount, :class => 'control-label' %>
    <div class="right-inner-addon">
      <span>%</span>
      <div class="controls">
        <%= f.text_field :discount, :class => 'form-control' %>
      </div>
    </div>
    <%= error_span(@product[:discount]) %>
  </div>

  <% if @product.new_record? %>
    <h3>Product Variants </h3>
    <div class="control-group">
      <%= f.fields_for :product_variants do |product_variant| %>
        <div class="controls variant">
          <%= product_variant.label :size, :class => 'control-label required' %>
          <%= product_variant.select :size, Product.size_options, { include_blank: true }, :class => 'form-control', required: true %>
          <%= product_variant.label :quantity, :class => 'control-label required' %>
          <%= product_variant.number_field :quantity, :class => 'form-control', required: true %>
          <%= product_variant.label :color, :class => 'control-label required' %>
          <%= product_variant.collection_select :color_id, @colors, :id, :name, { include_blank: true }, :class => 'form-control', required: true %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
  </div>
  <script>
    $("form").change(function () {
      if (!window.onbeforeunload) {
        window.onbeforeunload = function() {
          return "You have unsaved changes.";
        };
      };
    })

    $("form").submit(function () {
      window.onbeforeunload = null;
    });
  </script>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:title) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:description) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:price) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:category_id) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:brand_id) %></th>
      <th class="text-center">Product Variants</th>
      <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
      <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="text-center"><%= product.id %></td>
        <td class="text-center"><%= link_to product.title, product_path(product) %></td>
        <td class="text-center description" title="<%= product.description %>"><%= product.description %></td>
        <td class="text-center"><%= product.price %>$</td>
        <td class="text-center"><%= product.category.name %></td>
        <td class="text-center"><%= product.brand.name %></td>
        <td class="text-center">
          <% if product.product_variants.any? %>
            <%= link_to "Variants", product_product_variants_path(product.id), class: "variant" %>
          <% end %>
        </td>
        <td class="text-center"><%= product.created_at.strftime("%b %d, %Y") %></td>
        <td class="text-center">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_product_path,
              :class => 'btn btn-primary' %>
</div>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @product.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %>$</dd>
  
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/products/show_variant.html.erb
<div class="page-header">
<h2><%= @product.title %></h2>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="text-center">Variant_id</th>
      <th class="text-center">Size</th>
      <th class="text-center">Quantity</th>
      <th class="text-center">Color</th>
    </tr>
  </thead>
  <tbody>
    <% @product.product_variants.each  do |product_variant| %>
      <tr>
        <td class="text-center"><%= product_variant.id %></td>
        <td class="text-center"><%= product_variant.size %></td>
        <td class="text-center"><%= product_variant.quantity %></td>
        <td class="text-center"><%= product_variant.color.name %></td>
      </tr>
    <% end %>
  <tbody>
</table>